[versions]
kord-extensions = "1.6.0"
kordx-emoji = "0.5.0"
kotlin = "1.9.22"
kotlinx-coroutines = "1.7.3"
kotlinx-datetime = "0.5.0"
shadow = "8.1.1"
slf4j = "2.0.11"
sqldelight = "2.0.1"

[libraries]
kordextensions-kordextensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kordextensions-unsafe = { module = "com.kotlindiscord.kord.extensions:unsafe", version.ref = "kord-extensions" }

kordx-emoji = { module = "dev.kord.x:emoji", version.ref = "kordx-emoji" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
